[tools]
1password-cli = "latest"
age = "latest"
atuin = "latest"
"github:aldanial/cloc" = "v2.08"
cargo-binstall = "latest"
codex = "latest"
eza = "0.23.4"
fnox = "latest"
hcloud = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tiny = "latest"
usage = "latest"
zoxide = "latest"
node = "lts"

[settings]
experimental = true
install_before = "7d"  # only install versions released more than 7 days ago
env_cache = true
quiet = false

[settings.pipx]
uvx = true

[settings.python]
compile = false

[env]
PIPENV_VENV_IN_PROJECT = 0
PYTHONPYCACHEPREFIX = "{{ xdg_cache_home }}/pycache{{ cwd }}"
