tap "withgraphite/tap"
# Load/unload environment variables based on $PWD
brew "direnv"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Text interface for Git repositories
brew "tig"
# Terminal multiplexer
brew "tmux"
# Manage complex tmux sessions easily
brew "tmuxinator"
# Allows you to manage your stacked changes and submit them for review on GitHub
brew "withgraphite/tap/graphite"
vscode "amazonwebservices.codewhisperer-for-command-line-companion"
vscode "astro-build.astro-vscode"
vscode "asvetliakov.vscode-neovim"
vscode "bierner.markdown-mermaid"
vscode "bradlc.vscode-tailwindcss"
vscode "charliermarsh.ruff"
vscode "ckolkman.vscode-postgres"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "graphite.gti-vscode"
vscode "graphql.vscode-graphql-syntax"
vscode "kamikillerto.vscode-colorize"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.mypy-type-checker"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "rust-lang.rust-analyzer"
vscode "serenade.serenade"
vscode "sourcegraph.cody-ai"
vscode "sourcery.sourcery"
vscode "unifiedjs.vscode-mdx"
vscode "vadimcn.vscode-lldb"
vscode "vscodevim.vim"
vscode "will-wow.vscode-alternate-file"
vscode "withfig.fig"
go "github.com/KarnerTh/mermerd"
