gui:
  showDivergenceFromBaseBranch: arrowAndNumber
  mouseEvents: false

customCommands:
  - key: "v"
    context: "localBranches"
    command: "gh pr view {{.SelectedLocalBranch.Name}} --web"
    description: "Open PR in browser"
